# Full URL to the pages
url: "https://vasyaod.github.io/my-tracks"

# Base path
basePath: "/my-tracks"

# Caption of the site.
siteTitle: "Tracks"

# Header of the site
siteDescription: "This is description which you can change in the config file."

# Distance threshold (meters) for filtering
distanceThreshold: 20

# Time threshold (seconds) for splitting of tracks
timeThreshold: 600
