#!/bin/bash

set -e

sudo apt install python
sudo pip3 install tensorflow

export INPUT_DATA_PATH="$(pwd)/data-repo"
export OUTPUT_DATA_PATH="$(pwd)/pages-repo"

# Copy config file from data repo to viewer
cp -u data-repo/config.js code-repo/viewer/src || true

# Compile code of site/viewer
cd code-repo/viewer
npm install
npm run build
cd ../..

# Copy generated code and other resources...
cp code-repo/viewer/bundle.js pages-repo
cp code-repo/viewer/index.html pages-repo

# Data processing
cd code-repo/etl
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o youtube-dl
chmod +x youtube-dl
npm install
npm run lets-do-this
cd ../..

# Run site in dev mode
cp -R pages-repo/data code-repo/viewer
cp -R pages-repo/images code-repo/viewer
cd code-repo/viewer
npm install
npm run dev &
cd ../..

# Make preview/thumbnail for every trip
cd code-repo/previewer
npm install
npm run lets-do-this
cd ../..