name: Checks

#on: [pull_request]

on:
  push:
    branches: [ dev ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Check ETL
    #   run: |
    #     cd etl
    #     npm install
    #     node main.js

    # - name: Check Viewer
    #   run: |
    #     cd viewer
    #     npm install
    #     npm run build